### ISSUE TITLE
Publisher-related queries and behaviors for Rarebooks

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#1381]
As part of the project to port Rarebooks.info to a Stanford-hosted Spotlight exhibit (see [project charter](https://docs.google.com/document/d/1-o8yutZyxBcJ48S1O67qoTbHLBs0W4yyEBpYBS9D39U/edit)), Nicole has asked us to add features that support searching and sorting the items by publisher:

> * Deliverable 3.2: The exhibit allows search across all of the volumes or selected 
volumes (selected by title, author, *publisher*, date)
> * Deliverable 3.3: The exhibit provides a sortable list of search results (sortable by title, by author, *by publisher*)

This suggests the following (which she and Arcadia have confirmed):

* [ ] #1382 Add a publisher facet
* [ ] #1383 Sort search results by publisher
* [ ] #1384 Add publisher to field-based search
