### ISSUE TITLE
Enable visitors to search across exhibits

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1466]
The overall goals of this issue are to enable exhibit visitors to go to the [Exhibits landing page](https://exhibits.stanford.edu/) and:

- Conduct a search of item metadata across all published exhibits
- See results of matching items from all published exhibits in a single, consolidated result list
- Evaluate the results by sorting, using (limited) facets, and focusing on either individual result items or the exhibits that contain result items
- Navigate from a result item to the exhibit containing that item (which can be to an exhibit home page, an exhibit results page, or an exhibit item show page, depending on the landing page results context)

Specific work tickets related to this issue:

- [ ] #1520 - Add form for searching across exhibits to site sidebar
- [ ] #1524 - Add facets to site sidebar
- [ ] #1531 - Add site search results page with list view
- [ ] #1532 - Add gallery view to site search results page
- [ ] #1539 - Add Grouped by exhibit option to list view of site search results
- [ ] #1534 - Add Grouped by exhibit option to gallery view of site search results
