### ISSUE TITLE
Add a sidebar block to Searchworks record page when collection items are in exhibit(s)

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1468]
This is similar in many ways to #1465, but probably more technically challenging. Also, while the UI elements added with this proposal are very similar to those in #1465, I'd want @jvine to review because I'm making some assumptions about Searchworks design and that's really her domain. But the ideas below should be enough for us to discuss the feasibility of doing this for Searchworks collection records, in addition to Searchworks item records.

### Basic idea
When a visitor displays a Searchworks **collection** record page, we'd like to inform them of any exhibits in which any item of the current collection is part of. If we can do that, technically, then the UI display is fairly close to what is proposed in #1465. For example, assume that the visitor is looking at the  "Glen McLaughlin Collection of California as an Island" [collection record page in Searchworks](https://searchworks.stanford.edu/view/kw406zk5778), and that items from this collection are part of two published exhibits. We'd add the sidebar section indicated below to the collection record page (there is currently no sidebar on this page, but there is space for it):

<img width="1064" alt="searchworks-collection-page" src="https://user-images.githubusercontent.com/101482/72193991-1d39ed00-33c9-11ea-89c5-7d2c5ee4daa0.png">

### Sidebar details

- [ ] Add a heading using an `h2` with the label "Context" (JV might have other ideas)
- [ ] Style the heading similar to the other section heading on the page, including the border-bottom
- [ ] Add a sidebar box with all the same styling as the sidebar box specified in #1465
- [ ] Give the sidebar box heading the label "Exhibits" (this is different from #1465)
- [ ] Add a line of text `Items from this collection are featured in:` at the top of the box content area
- [ ] Display each exhibit an item from the current collection is in, displayed exactly like the equivalent components (B, C, and D) are in #1465

### Multiple exhibit considerations
- [ ] If items from the current collection appear in more than one exhibit, and we know how many items from the current collection are in each exhibit, order the list of exhibits in the sidebar box by count, descending (i.e., the exhibit with the most items from the collection is listed first).

- [ ] If there are more than five exhibits with items from the current collection, add a link with the label `See all [x] exhibits` after the fifth one. For example if the current collection items appear in 7 exhibits (example is in the `MD` viewport where sidebar takes full-width of the page):

<img width="787" alt="5-exhibits" src="https://user-images.githubusercontent.com/101482/72195487-c683e180-33cf-11ea-819d-1345e1f56a95.png">

- [ ] If the user selects the "See all" link, expand the box to show all exhibits:

<img width="787" alt="7-exhibits" src="https://user-images.githubusercontent.com/101482/72195524-ee734500-33cf-11ea-80f5-fb0c7d49d852.png">

- [ ] Not shown in the mockup above, but when the list is expanded, show a link to collapse the list back to 5 exhibits, with the label "See fewer exhibits".
