### ISSUE TITLE
(377 parent) Feature enhancement: Expand display of indexed metadata fields

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#377]
Display of indexed metadata fields is currently limited. Numerous curators are requesting enhanced display: Reagan Murphy-Kao, Ray Hegemeier, Josh Schneider, Amy Hodge, Zhaohui Xue, Giovanni Svevo & more.  

Current Spotlight display is documented here:
https://consul.stanford.edu/display/DIGMETADATA/MODS+indexing+and+display+in+SearchWorks+and+Spotlight#MODSindexinganddisplayinSearchWorksandSpotlight-B.SpotlightMODSdisplay(fromMODSindirectly,asindexedinSolr)

Arcadia Falcone is meeting with exhibit creators to obtain more specifics regarding this enhancement request. When specs/acceptance criteria are gathered, additional tickets will be created.

Related tickets, all Feature enhancement for metadata display:...

- [ ] Index <relatedItem displayLabel=“Series”><title> as series #384
- [ ] Support active URL links in metadata display and narrative text #385 
- [ ] Index end date of ranges #381 

- [x] Index identifiers for display #383 

- [ ] Don’t include <mods><genre> in topic index #382 
- [ ] Index names separately by role (as well as collectively) #380 

- [ ] Index notes separately by display label #379

- [ ] Change criteria for author sort indexing #447

**Comment by caaster** [comment]
Arcadia has met with several exhibit admins to gather information about their use cases & preferences. This information is preliminary, but provides an excellent window of info/understanding to exhibit admin needs. See attached spreadsheet.
[spotlight user interview data.xlsx](https://github.com/sul-dlss/exhibits/files/559182/spotlight.user.interview.data.xlsx)

**Comment by arcadiafalcone** [comment]
Acceptance criteria matrix with more information about these issues.
[github_ticket_info_20170118.docx](https://github.com/sul-dlss/exhibits/files/717960/github_ticket_info_20170118.docx)

**Comment by blalbrit** [comment]
@caaster @arcadiafalcone Parker will require the full suite of MODS fields that we would support in SW. It's hard to tell from this ticket - but how close are we to that now?

**Comment by arcadiafalcone** [comment]
@blalbrit  This documentation as to what is indexed in Spotlight is up to date (see table B): https://consul.stanford.edu/display/DIGMETADATA/MODS+indexing+and+display+in+SearchWorks+and+Spotlight

The short version is that SW iterates through most available MODS fields for display rather than using Solr indexes as Spotlight does, so Spotlight metadata display is significantly more limited, especially in terms of a) repeated fields (usually only the first instance is indexed) and b) attributes like displayLabel and type (only certain attributes, or their absence, result in the field being indexed). I can do a more detailed rundown of what is currently not available in Spotlight if that would be helpful. (It's on my list of things to do anyway, at request of exhibit owners.)

**Comment by caaster** [comment]
+1 for documentation of what is not currently available in Spotlight. This would be very helpful to me/ Spotlight service team as well.

**Comment by caaster** [comment]
@blalbrit FWIW, Chris explained to me that several of the tickets listed have maintenance implications, making them challenging to implement. I am very interested in how Parker needs are addressed by Spotlight, and to learn whether or not it will be feasible to leverage any Parker-Spotlight work in this vein for Spotlight at Stanford.

**Comment by arcadiafalcone** [comment]
@blalbrit @caaster Spreadsheet attached covering what Spotlight does and doesn't index in MODS terms. I set up the data so that you should be able to filter on FALSE in the "Indexed for display?" or "Indexed for faceting?" columns and see everything not currently indexed in either category.

[spotlight_mods_comprehensive.xlsx](https://github.com/sul-dlss/exhibits/files/777724/spotlight_mods_comprehensive.xlsx)

**Comment by caaster** [comment]
This ticket has largely been superseded by a number of recast & carefully articulated tickets about metadata indexing & display. I am not closing this ticket yet -- until I determine if we need any of the history captured in this ticket.
