### ISSUE TITLE
Bibliographic Items as First-Class Objects in Index

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#572]
Instead of creating a user-story to express this story, I'm going to assume that the user-stories already captured for the Parker sprint will suffice as background for this. In order to support those bibliographic stories, the team determined that bibliographic items should be first-class objects in the index.

Acceptance criteria:
* [x] ability to index a bibliographic item from a fixture or import process #583
* [x] ability to express a bibliographic record in a search result (with design work underway - #575) split to #584
* [x] ability to provide citations of these first-class objects in a manuscript item view display, aggregating all bibliographic objects "about" a specific manuscript item #585

Open questions:
* Is it possible to import enough information from an external bibliography to satisfy user needs, or is it preferable to link out to (say) a Zotero bibliographic item for additional information
* what does an item view for a bibliographic record look like? (or is it necessary?)
