### ISSUE TITLE
Ingest in Bulk for Bibliographic Items

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#574]
Assumptions:

1) we will start with an export in a standard format from Zotero of the Parker bibliography (instead of relying on the Zotero API)
2) the ingest needs to be repeatable by an exhibit admin/curator (so UI implications for the dashboard)

Story:
As an exhibit admin/curator I want to be able to upload my bibliography on a regular (weekly) basis. I probably want to do this as a full upload (rather than just new items) because we often edit existing bibliographic items with manuscript-specific notes.

Acceptance criteria:
* [x] functional UI for upload in dashboard (design to be done in #586)
* [x] ability to find bibliographic items (or appearances of those items) in search results
* [x] ability to see the bibliographic citations on each manuscript view page #585
* [x] ability to index full Parker bibliography #616

**Comment by mejackreed** [comment]
Potential problems:
 - how large is this file (the complete bibliography)? What format is it? What formats can we get?
 - We have an add/update/delete problem. How do we track citations and when they are updated? (Does zotero provide a unique id?)

**Comment by blalbrit** [comment]
CSV -> 7.1 MB
BIB -> 4.7 MB
Endnote XML -> 9.7 MB

Unclear to me yet which is the ideal in terms of content output and mapping, still looking into the various formats.

**Comment by blalbrit** [comment]
<img width="229" alt="screenshot 2017-09-25 14 57 24" src="https://user-images.githubusercontent.com/796990/30833028-2f1a5d08-a202-11e7-841a-32130e030a90.png">

Available formats.

**Comment by blalbrit** [comment]
Examples of the three formats can be seen here: https://drive.google.com/drive/folders/0B1IxI8f59JQkdW5sSWdpci10WE0?usp=sharing

**Comment by blalbrit** [comment]
My understanding is that each citation has a unique identifier, see:

https://www.zotero.org/groups/1051392/parkerlibrary/items/itemKey/UDUBFIMB

Where UDUBFIMB should be a persistent identifier. That should be verified.
