### ISSUE TITLE
ability to provide citations of these first-class objects in a manuscript item view display, aggregating all bibliographic objects "about" a specific manuscript item

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#585]
Splitout from #572. Depends on #589, and #600.

See https://github.com/sul-dlss/exhibits/issues/578#issuecomment-332332320 for background

- [x] Integrate citeproc gem to implement reference style (Chicago, Author-Date, ascending) (PR #602)
- [x] Handle embedded LaTeX in bibliography items (`{}`, `\textit{}`, etc.) (PR #602)
- [x] Query Solr for all bibliography items relating to given manuscript, needs to be gated by exhibit (requires #589)
- [x] Fetch BibTeX for all the relevant bibliography items (requires #600)
- [ ] Add styled, sorted bibliography to show page (#576)

**Comment by mejackreed** [comment]
Dependent on #578 and #583

**Comment by mejackreed** [comment]
Potentially will require an asynchronously lookup to Solr.

**Comment by drh-stanford** [comment]
@blalbrit the Parker bibliography has LaTeX markup in the titles (and possibly elsewhere). For example, `This is \textit{my {Capitalized Title}}`. Is this a consistent practice for the Parker folks? When rendering the bibliography can they be ignored, or should we be rendering them as HTML?

**Comment by blalbrit** [comment]
@drh-stanford Weird. The Parker folks aren't doing that (they were just entering text into Endnote and FileMakerPro) - must be an artifact from some export/import process. Those can be ignored, I think. Can you tell me what Zotero record that example is from? I'll check the source data just to make sure.

**Comment by drh-stanford** [comment]
@blalbrit it looks like they are putting HTML markup in the records. The BibTeX export must be converting it into TeX commands.

See (Whatley 1986) -- there is HTML in the title.

**Comment by blalbrit** [comment]
@drh-stanford Great - thanks for the example. That is an artifact of the EndNote export. Original looks like:
<img width="294" alt="screenshot 2017-09-27 14 51 24" src="https://user-images.githubusercontent.com/796990/30939772-7b3e62c8-a393-11e7-90bd-95a2ccc7eadf.png">
Please ignore that mark-up for the work that you all are doing.

**Comment by drh-stanford** [comment]
Currently blocked by #589 and #600.
