### ISSUE TITLE
Implement search results for Canvas/Page/AnnoList

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#830]
Design discussed and implemented in #726 

Spin off tickets:
 - [x] #841 Provide different title sort
 - [x] #831 add manuscript title to page detail title
 - [x] #832 add identifier to page detail title

Basic first pass design here:

![design](https://user-images.githubusercontent.com/101482/32465663-78c23d66-c301-11e7-98d0-4245b08b79fb.png)
