### ISSUE TITLE
Add constituent relatedItem support to mods_display gem

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/exhibits#887]
- [x] Write custom configuration of mods_display gem (see Purl for example) that does what we want for pre-constituent support (see https://github.com/sul-dlss/exhibits/issues/899)
- [x] Update mods_display gem to include support for extracting constituent relatedItems - #905
- [ ] Add custom configuration for the constituent display
- [x] Add view logic for hierarchical display of the metadata  - #905

Design in #799 

![mock](https://user-images.githubusercontent.com/101482/32629677-3c778e76-c557-11e7-94ab-f8ddb7d05559.png)

**Comment by ggeisler** [comment]
Just a reminder that the design above is only a general first-pass. I discussed the idea with @jvine last week and she is going to do more thinking and design for this to make sure the solution makes sense for other contexts in which the MODS Display gem would be shown.

**Comment by drh-stanford** [comment]
I'll be using https://purl.stanford.edu/hp566jq8781.mods for fixture data, and only the `<relatedItem type="constituent">` will be supported if I understand the requirements correctly.

**Comment by drh-stanford** [comment]
I have a branch going in the mods_display gem here: https://github.com/sul-dlss/mods_display/compare/37-constituent-relatedItem

**Comment by drh-stanford** [comment]
I've got the mods_display branch setup for basic constituent extract and the start of integrating it into the MODS display modal:

![screen shot 2017-11-15 at 4 22 06 pm](https://user-images.githubusercontent.com/1861171/32867302-2de04456-ca21-11e7-999f-1a01c8e5187d.png)

**Comment by drh-stanford** [comment]
also see https://github.com/sul-dlss/exhibits/issues/905

**Comment by drh-stanford** [comment]
switching over to the other metadata tickets as this is more advanced here -- see #910

**Comment by mejackreed** [comment]
We think that #903 may include the design needed to complete.

**Comment by mejackreed** [comment]
I think all of these items are now resolved. Feel free to reopen or split off if something isn't shipped.
