### ISSUE TITLE
Ordering & grouping of metadata

### ISSUE THREAD

**Issue by jvine** [sul-dlss/exhibits#910]
After analysis discussion with gryphon-search and @arcadiafalcone: 
- the grouping and ordering in SearchWorks (and by default applied to PURL) was done to support specific goals and tasks on the show page that do not apply in the same way to either PURL or Exhibits in general, or Parker in particular
- there is a general feeling that a consistent grouping of MODS might be desirable, but will require substantially more analysis before it can be applied broadly across Exhibits (what seems to work for Parker doesn't fit all metadata equally well) or elsewhere
- for now, I am proposing that the metadata be displayed in its standard order, with some exceptions/adjustments (listed below).

---
- [x] 1. Apply SW/PURL visual design to the `<dl>` elements. (Transform `<dt>` to uppercase; indent `<dl>`; adjust line-spacing.) #918

- [x] 2. Where the title exists as a heading on the page, do not include it in the labelled metadata. Split out to #922

- [x] 3. Use `<roleTerm>` as labels in place of "Contributor" or "Author/Creator" labels. Split out to #936 

- [x] 4. Convert the "Contents" display from '--' delimiters to a bulleted list (without show/hide behaviour in the context of the modal):
  - [x] Change `--` into `<li>` list (See https://github.com/sul-dlss/mods_display/pull/42)
  - [x] Suppress Contents in Parker exhibits closed in #944

- [x] 5. Separate the rights & access metadata into a separate section with a heading of "Access conditions" (follows PURL and SW) (See #920)

- [x] 6. Display nested metadata (currently not displayed at all by mods_display) with show/hide behaviour (see #903 and #905). Note that the types (constituent and host) are labelled separately.

7. Consider displaying curator-added exhibit tags in the full metadata display, between the main metadata and Access conditions (not Parker-specific).

---

![mods_display1](https://user-images.githubusercontent.com/6945691/32923850-a02956c4-caee-11e7-924d-bfc18aaf1b50.jpg)

![mods_display2](https://user-images.githubusercontent.com/6945691/32923862-a65427a4-caee-11e7-9006-8fe77568045f.jpg)

**Comment by jvine** [comment]
@drh-stanford based on a separate discussion, i think we intend to suppress the Table of Contents (i.e. item 4 above) from the metadata view, and include it only on the Show page. I'm not sure whether this is a Parker-specific change; I'll verify. Let me know if you have questions or this needs a separate issue.

**Comment by mejackreed** [comment]
@jvine ref #2. Previously we had implemented the page title / heading as : `Metadata: Title` should we keep that? Or just change to `Title` ?

**Comment by jvine** [comment]
Hm. I prefer just `Title` (I think `Metadata: ` slightly obscures the title) - but it's good practice to title the popup itself. I don't want to override @ggeisler without his input. Let's leave `Metadata: ` in place for now.

**Comment by drh-stanford** [comment]
Per discussion on Slack: the `tableOfContents` should be shown as a bulleted list in the MODS display modal, and that behavior is the same across applications. There's an open issue on whether we can/should suppress the table of contents entirely for Parker on the MODS modal.

I've put in a PR to mods_display that does the list conversion.

**Comment by drh-stanford** [comment]
@blalbrit do you have an example Parker druid that has contributor data (3) for that object? I'm seeing contributor data in the *constituent* related items, but not for the object itself. The screenshot example (https://purl.stanford.edu/hp566jq8781.mods) doesn't seem to have a contributor.

**Comment by blalbrit** [comment]
@drh-stanford - for the most part, the source metadata doesn't have contributor information at the object level, it's primarily in the constituent related items. Reason for this is Parker-specific... in almost all cases, we do not know who CREATED the object, we only know who created the texts that are in the object. It's a weird manuscript semantic thing - and is definitely different from more general content.

**Comment by drh-stanford** [comment]
@jvine for (3) did you want to remove the (roles) after the name. For example,

```
Contributor:
  John Doe (Lithographer)
```

would become:

```
Lithographer:
  John Doe
```

or do you just want to change the label, i.e.,

```
Lithographer:
  John Doe (Lithographer)
```

**Comment by jvine** [comment]
@drh-stanford remove the role after the name.

**Comment by jkeck** [comment]
Is this behavior that is just specific to Exhibit's implementation of ModsDisplay or should this also be put upstream in ModsDisplay?

**Comment by jvine** [comment]
Upstream would be ideal, @jkeck

**Comment by drh-stanford** [comment]
@jvine what should the label say if the role is author or creator? and what if there's no role information?

**Comment by arcadiafalcone** [comment]
If the role is "author" or "creator", that should be the label. Ditto for "contributor". I'm almost inclined to suggest "Associated with" or "Associated name" if there's no role -- @jvine what do you think?

**Comment by jvine** [comment]
Agree, author/creator/contributor are fine as labels when they are the specified role, we just don't want them as a generic labels when there is another role specified. When there's NO role then use a generic label - I like Arcadia's suggestion of "Associated with".

**Comment by jvine** [comment]
Additional note:  Multiple people with the same role should be grouped under one label (ideally in a list!). The same person with multiple roles should be splatted out into multiple label/value pairs.

**Comment by arcadiafalcone** [comment]
BTW "Associated name" is an actual role term in the MARC relator list, so it might turn up on its own.

**Comment by drh-stanford** [comment]
@jvine do you have any MODS examples of the multiple people having the same role?

**Comment by jvine** [comment]
@drh-stanford I only know it's possible. @arcadiafalcone ?

**Comment by drh-stanford** [comment]
I've broken out (3) into its own ticket #936

**Comment by arcadiafalcone** [comment]
@drh-stanford @jvine I'll find something.

**Comment by drh-stanford** [comment]
the only example i have is a fake example here: https://github.com/sul-dlss/mods_display/blob/master/spec/fixtures/name_fixtures.rb#L134-L150
so it'd be helpful to get a real example.

**Comment by arcadiafalcone** [comment]
Here's one: vn199zb9806

**Comment by arcadiafalcone** [comment]
Multiple creators with same role example: fs947tw3404

**Comment by ggeisler** [comment]
@mejackreed @jvine Regarding the [comment](https://github.com/sul-dlss/exhibits/issues/910#issuecomment-345733937) about the heading/title of the modal, thanks for waiting for my input but I'm completely fine with not including "Metadata" in the heading. I think I just put that there in my original mockup when I wasn't sure if we wanted to go with the modal approach or not and wanted to make clear what the modal was about. I agree it's not actually needed.

**Comment by mejackreed** [comment]
Marking this as complete as all items appear to be done & :shipit:
